on:
  push:


defaults:
  run:
    working-directory: ./kjell

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - run: sam build --use-container
      - name: deploy
        if: github.ref == 'refs/heads/main'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name app2022s --s3-bucket lambda-sam-template-2022 --capabilities CAPABILITY_IAM --region eu-west-1
